---
## Playbook to show version on IOS  

- hosts: CSR_Routers

  tasks:
   - name: Show Version 
     ios_command: 
       commands: show ip int brief
     register: version 

   - name: Save output to ~/afne/
     copy:
       content: "{{version.stdout[0]}}"
       dest: "~/afne/{{inventory_hostname}}-version.txt"
